/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import Algoritmo.Burbuja;
import Algoritmo.BurbujaBidireccional;
import Algoritmo.CountingSort;
import Algoritmo.Inserccion;
import Algoritmo.MezclaDirecta;
import Algoritmo.OrdenamientoAB;
import Algoritmo.Quicksort;
import Algoritmo.RadixSort;
import Algoritmo.SelectionSort;
import Algoritmo.ShellSort;
import Estructura.ArbolBinarioF;
import Estructura.ColaCircular;
import Estructura.ColaDoble;
import Estructura.ColaPrioridades;
import Estructura.ColaSimple;
import Estructura.Grafo;
import Estructura.ListaDoble;
import Estructura.ListaDobleCircular;
import Estructura.ListaSimple;
import Estructura.ListaSimpleCircular;
import Estructura.Pila;

/**
 *
 * @author andre
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Estructuras
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnArbol = new javax.swing.JButton();
        btnColaP = new javax.swing.JButton();
        btnColaC = new javax.swing.JButton();
        btnColaD = new javax.swing.JButton();
        btnListaS = new javax.swing.JButton();
        btnListaDC = new javax.swing.JButton();
        btnListaD = new javax.swing.JButton();
        btnColaS = new javax.swing.JButton();
        btnGrafo = new javax.swing.JButton();
        btnPila = new javax.swing.JButton();
        btnListaSC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnShell = new javax.swing.JButton();
        btnSel = new javax.swing.JButton();
        btnInserc = new javax.swing.JButton();
        btnBubbleBi = new javax.swing.JButton();
        btnCount = new javax.swing.JButton();
        btnRadix = new javax.swing.JButton();
        btnQuick = new javax.swing.JButton();
        btnAB = new javax.swing.JButton();
        btnMerge = new javax.swing.JButton();
        btnBubble = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Estructuras");

        btnArbol.setText("Arbol Binario");
        btnArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArbolActionPerformed(evt);
            }
        });

        btnColaP.setText("Cola de prioridades");
        btnColaP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaPActionPerformed(evt);
            }
        });

        btnColaC.setText("Cola circular");
        btnColaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaCActionPerformed(evt);
            }
        });

        btnColaD.setText("Cola doble");
        btnColaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaDActionPerformed(evt);
            }
        });

        btnListaS.setText("Lista simple");
        btnListaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaSActionPerformed(evt);
            }
        });

        btnListaDC.setText("Lista doble circular");
        btnListaDC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDCActionPerformed(evt);
            }
        });

        btnListaD.setText("Lista doble");
        btnListaD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaDActionPerformed(evt);
            }
        });

        btnColaS.setText("Cola simple");
        btnColaS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaSActionPerformed(evt);
            }
        });

        btnGrafo.setText("Grafo");
        btnGrafo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrafoActionPerformed(evt);
            }
        });

        btnPila.setText("Pila");
        btnPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilaActionPerformed(evt);
            }
        });

        btnListaSC.setText("Lista simple circular");
        btnListaSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaSCActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Algoritmos");

        btnShell.setText("Shellsort");
        btnShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShellActionPerformed(evt);
            }
        });

        btnSel.setText("Selectionsort");
        btnSel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelActionPerformed(evt);
            }
        });

        btnInserc.setText("Insercción");
        btnInserc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsercActionPerformed(evt);
            }
        });

        btnBubbleBi.setText("Burbuja bidireccional");
        btnBubbleBi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleBiActionPerformed(evt);
            }
        });

        btnCount.setText("Countingsort");
        btnCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountActionPerformed(evt);
            }
        });

        btnRadix.setText("Radixsort");
        btnRadix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadixActionPerformed(evt);
            }
        });

        btnQuick.setText("Quicksort");
        btnQuick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickActionPerformed(evt);
            }
        });

        btnAB.setText("Árbol binario");
        btnAB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnABActionPerformed(evt);
            }
        });

        btnMerge.setText("Mezcla directa");
        btnMerge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMergeActionPerformed(evt);
            }
        });

        btnBubble.setText("Burbuja");
        btnBubble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBubbleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnColaS, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnListaD, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(btnListaDC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnListaS, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnColaC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnColaD, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btnColaP, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnListaSC, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnPila, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnShell, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnBubble, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnBubbleBi, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(btnAB, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(btnRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(30, 30, 30)
                                            .addComponent(btnInserc, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(btnGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColaP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColaC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColaD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnColaS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListaDC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListaSC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPila, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGrafo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBubble, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBubbleBi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMerge, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRadix, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQuick, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShell, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGrafoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrafoActionPerformed
        Grafo gra = new Grafo();
        gra.setVisible(true);
    }//GEN-LAST:event_btnGrafoActionPerformed

    private void btnArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArbolActionPerformed
        ArbolBinarioF arbol = new ArbolBinarioF();
        arbol.setVisible(true);
    }//GEN-LAST:event_btnArbolActionPerformed

    private void btnColaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaCActionPerformed
        ColaCircular cola = new ColaCircular();
        cola.setVisible(true);
    }//GEN-LAST:event_btnColaCActionPerformed

    private void btnColaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaDActionPerformed
        ColaDoble cola = new ColaDoble();
        cola.setVisible(true);
    }//GEN-LAST:event_btnColaDActionPerformed

    private void btnColaPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaPActionPerformed
        ColaPrioridades cola = new ColaPrioridades();
        cola.setVisible(true);
    }//GEN-LAST:event_btnColaPActionPerformed

    private void btnColaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaSActionPerformed
        ColaSimple cola = new ColaSimple();
        cola.setVisible(true);
    }//GEN-LAST:event_btnColaSActionPerformed

    private void btnListaDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDActionPerformed
        ListaDoble lista = new ListaDoble();
        lista.setVisible(true);
    }//GEN-LAST:event_btnListaDActionPerformed

    private void btnListaDCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaDCActionPerformed
        ListaDobleCircular lista = new ListaDobleCircular();
        lista.setVisible(true);
    }//GEN-LAST:event_btnListaDCActionPerformed

    private void btnListaSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaSActionPerformed
        ListaSimple lista = new ListaSimple();
        lista.setVisible(true);
    }//GEN-LAST:event_btnListaSActionPerformed

    private void btnListaSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaSCActionPerformed
        ListaSimpleCircular lista = new ListaSimpleCircular();
        lista.setVisible(true);
    }//GEN-LAST:event_btnListaSCActionPerformed

    private void btnPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilaActionPerformed
        Pila pi = new Pila();
        pi.setVisible(true);
    }//GEN-LAST:event_btnPilaActionPerformed

    private void btnBubbleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleActionPerformed
        Burbuja bu = new Burbuja();
        bu.setVisible(true);
    }//GEN-LAST:event_btnBubbleActionPerformed

    private void btnBubbleBiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBubbleBiActionPerformed
        BurbujaBidireccional bu = new BurbujaBidireccional();
        bu.setVisible(true);
    }//GEN-LAST:event_btnBubbleBiActionPerformed

    private void btnCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountActionPerformed
        CountingSort cou = new CountingSort();
        cou.setVisible(true);
    }//GEN-LAST:event_btnCountActionPerformed

    private void btnInsercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsercActionPerformed
        Inserccion ins = new Inserccion();
        ins.setVisible(true);
    }//GEN-LAST:event_btnInsercActionPerformed

    private void btnMergeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMergeActionPerformed
        MezclaDirecta mes = new MezclaDirecta();
        mes.setVisible(true);
    }//GEN-LAST:event_btnMergeActionPerformed

    private void btnABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnABActionPerformed
        OrdenamientoAB ab = new OrdenamientoAB();
        ab.setVisible(true);
    }//GEN-LAST:event_btnABActionPerformed

    private void btnQuickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickActionPerformed
        Quicksort qs = new Quicksort();
        qs.setVisible(true);
    }//GEN-LAST:event_btnQuickActionPerformed

    private void btnRadixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadixActionPerformed
        RadixSort rad = new RadixSort();
        rad.setVisible(true);
    }//GEN-LAST:event_btnRadixActionPerformed

    private void btnSelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelActionPerformed
        SelectionSort ss = new SelectionSort();
        ss.setVisible(true);
    }//GEN-LAST:event_btnSelActionPerformed

    private void btnShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShellActionPerformed
        ShellSort shell = new ShellSort();
        shell.setVisible(true);
    }//GEN-LAST:event_btnShellActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAB;
    private javax.swing.JButton btnArbol;
    private javax.swing.JButton btnBubble;
    private javax.swing.JButton btnBubbleBi;
    private javax.swing.JButton btnColaC;
    private javax.swing.JButton btnColaD;
    private javax.swing.JButton btnColaP;
    private javax.swing.JButton btnColaS;
    private javax.swing.JButton btnCount;
    private javax.swing.JButton btnGrafo;
    private javax.swing.JButton btnInserc;
    private javax.swing.JButton btnListaD;
    private javax.swing.JButton btnListaDC;
    private javax.swing.JButton btnListaS;
    private javax.swing.JButton btnListaSC;
    private javax.swing.JButton btnMerge;
    private javax.swing.JButton btnPila;
    private javax.swing.JButton btnQuick;
    private javax.swing.JButton btnRadix;
    private javax.swing.JButton btnSel;
    private javax.swing.JButton btnShell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
